import { createContext, useContext, useMemo, useState } from "react";

const common = {
  en: {
    nav: ["Prototype", "Features", "How it works", "Goals", "Ecosystem", "Contact"],
    login: "Login",
    signin: "Sign in",
    getInTouch: "Get in touch",
    heroBadge: "Smart Farming · IoT · Live Readings",
    heroTitle1: "Farming,",
    heroTitle2: " connected",
    heroTitle3: "from soil to screen.",
    heroBody: "CropConnect is a field-to-phone IoT platform. Real sensors measure soil, water and climate in your farm, and our multilanguage app and web dashboard turn that data into decisions farmers can act on instantly.",
    explore: "Explore the platform",
    talkTeam: "Talk to the team",
    heroFacts: ["7+ Indian languages", "Works offline in low-signal fields", "Hardware-ready REST API"],
    impact: ["average water saved on monitored plots", "regional languages supported in-app", "sensor telemetry with smart alerts", "setup cost for the farmer - pay per node"],
    prototypeEyebrow: "The hardware",
    prototypeTitle: "Real prototype.",
    prototypeTitleItalic: " Real field.",
    prototypeBody: "Our physical build is already assembled - a modular sensor node wired into a gateway that streams live telemetry to the CropConnect cloud.",
    featuresEyebrow: "Everything in the app",
    featuresTitle: "Built for the farmer,",
    featuresItalic: " not the engineer.",
    featuresBody: "CropConnect is more than a dashboard. It is a full companion app, in the farmer's language, for the decisions that matter every day.",
    howEyebrow: "How the idea is implemented",
    howTitle: "From soil, to signal,",
    howItalic: " to screen.",
    howBody: "A four-layer architecture keeps hardware cheap, the cloud stateless and the app effortless for end-users.",
    goalsEyebrow: "Roadmap",
    goalsTitle: "What we ship now.",
    goalsItalic: "What we build next.",
    goalsBody: "CropConnect is designed to work on day one and keep compounding value as more nodes, farmers and crops join the network.",
    benefitsEyebrow: "Why it matters",
    benefitsTitle: "Benefits farmers feel",
    benefitsItalic: " in one season.",
    ecosystemEyebrow: "The ecosystem",
    ecosystemTitle: "One node today.",
    ecosystemItalic: "A network tomorrow.",
    ecosystemBody: "CropConnect is built as a platform, not a product. As more farms go online, every new data point compounds value for neighbours, co-ops, researchers and the supply chain.",
    appEyebrow: "The mobile app",
    appTitle: "In the farmer's",
    appItalic: " own words.",
    appBody: "CropConnect ships with a multilanguage interface, voice-ready labels and icons farmers can read at a glance.",
    contactEyebrow: "Talk to us",
    contactTitle: "Let's plant the",
    contactItalic: "first node together.",
    contactBody: "Whether you are a farmer, FPO, researcher, integrator or investor, tell us what you're working on and we'll reply within a day.",
    footerBody: "A field-to-phone IoT platform for modern farming. Built open, built multilingual, built for every farm.",
  },
  hi: {
    nav: ["प्रोटोटाइप", "विशेषताएं", "कैसे काम करता है", "लक्ष्य", "इकोसिस्टम", "संपर्क"],
    login: "लॉगिन",
    signin: "साइन इन",
    getInTouch: "संपर्क करें",
    heroBadge: "स्मार्ट खेती · IoT · लाइव रीडिंग",
    heroTitle1: "खेती,",
    heroTitle2: " कनेक्टेड",
    heroTitle3: "मिट्टी से स्क्रीन तक.",
    heroBody: "CropConnect खेत से फोन तक का IoT प्लेटफॉर्म है. सेंसर आपके खेत की मिट्टी, पानी और मौसम मापते हैं और ऐप उसे तुरंत काम की सलाह में बदलता है.",
    explore: "प्लेटफॉर्म देखें",
    talkTeam: "टीम से बात करें",
    heroFacts: ["7+ भारतीय भाषाएं", "कम नेटवर्क में ऑफलाइन काम", "हार्डवेयर-रेडी REST API"],
    impact: ["निगरानी वाले खेतों में औसत पानी बचत", "ऐप में क्षेत्रीय भाषाएं", "स्मार्ट अलर्ट के साथ सेंसर डेटा", "किसान के लिए सेटअप लागत - प्रति नोड भुगतान"],
    prototypeEyebrow: "हार्डवेयर",
    prototypeTitle: "असली प्रोटोटाइप.",
    prototypeTitleItalic: " असली खेत.",
    prototypeBody: "हमारा मॉड्यूलर सेंसर नोड तैयार है और गेटवे से जुड़कर लाइव डेटा CropConnect क्लाउड तक भेजता है.",
    featuresEyebrow: "ऐप में सब कुछ",
    featuresTitle: "किसान के लिए बनाया,",
    featuresItalic: " इंजीनियर के लिए नहीं.",
    featuresBody: "CropConnect सिर्फ डैशबोर्ड नहीं, किसान की भाषा में रोज़ के फैसलों का पूरा साथी ऐप है.",
    howEyebrow: "कैसे लागू होता है",
    howTitle: "मिट्टी से सिग्नल,",
    howItalic: " फिर स्क्रीन तक.",
    howBody: "चार-लेयर सिस्टम हार्डवेयर को सस्ता, क्लाउड को तेज़ और ऐप को आसान रखता है.",
    goalsEyebrow: "रोडमैप",
    goalsTitle: "अभी क्या बन रहा है.",
    goalsItalic: "आगे क्या बनेगा.",
    goalsBody: "CropConnect पहले दिन से काम करने और नए किसानों, फसलों और नोड्स के साथ बढ़ने के लिए बनाया गया है.",
    benefitsEyebrow: "क्यों जरूरी है",
    benefitsTitle: "किसानों को दिखने वाले फायदे",
    benefitsItalic: " एक सीजन में.",
    ecosystemEyebrow: "इकोसिस्टम",
    ecosystemTitle: "आज एक नोड.",
    ecosystemItalic: "कल पूरा नेटवर्क.",
    ecosystemBody: "CropConnect एक प्लेटफॉर्म है. जितने खेत ऑनलाइन आते हैं, डेटा उतना ही किसानों, FPO और शोधकर्ताओं के लिए उपयोगी बनता है.",
    appEyebrow: "मोबाइल ऐप",
    appTitle: "किसान की",
    appItalic: " अपनी भाषा में.",
    appBody: "CropConnect में बहुभाषी इंटरफेस, आवाज़-तैयार लेबल और साफ आइकन हैं जिन्हें किसान आसानी से पढ़ सके.",
    contactEyebrow: "हमसे बात करें",
    contactTitle: "आइए पहला",
    contactItalic: "नोड साथ लगाएं.",
    contactBody: "आप किसान, FPO, शोधकर्ता या निवेशक हों, हमें बताइए आप क्या बना रहे हैं. हम एक दिन में जवाब देंगे.",
    footerBody: "आधुनिक खेती के लिए खेत से फोन तक IoT प्लेटफॉर्म. खुला, बहुभाषी और हर खेत के लिए बनाया गया.",
  },
  mr: {
    nav: ["प्रोटोटाइप", "वैशिष्ट्ये", "कसे काम करते", "ध्येये", "इकोसिस्टम", "संपर्क"],
    login: "लॉगिन",
    signin: "साइन इन",
    getInTouch: "संपर्क करा",
    heroBadge: "स्मार्ट शेती · IoT · लाईव्ह रीडिंग",
    heroTitle1: "शेती,",
    heroTitle2: " जोडलेली",
    heroTitle3: "मातीपासून स्क्रीनपर्यंत.",
    heroBody: "CropConnect हे शेतापासून फोनपर्यंतचे IoT प्लॅटफॉर्म आहे. सेन्सर माती, पाणी आणि हवामान मोजतात आणि अॅप त्यातून त्वरित निर्णय देते.",
    explore: "प्लॅटफॉर्म पाहा",
    talkTeam: "टीमशी बोला",
    heroFacts: ["7+ भारतीय भाषा", "कमी सिग्नलमध्ये ऑफलाइन", "हार्डवेअर-रेडी REST API"],
    benefitsTitle: "शेतकऱ्यांना जाणवणारे फायदे",
    featuresTitle: "शेतकऱ्यासाठी बनवलेले,",
    featuresItalic: " इंजिनिअरसाठी नाही.",
    appTitle: "शेतकऱ्याच्या",
    appItalic: " स्वतःच्या भाषेत.",
  },
  te: {
    nav: ["ప్రోటోటైప్", "ఫీచర్లు", "ఇది ఎలా పనిచేస్తుంది", "లక్ష్యాలు", "ఎకోసిస్టమ్", "సంప్రదించండి"],
    login: "లాగిన్",
    signin: "సైన్ ఇన్",
    getInTouch: "సంప్రదించండి",
    heroBadge: "స్మార్ట్ వ్యవసాయం · IoT · లైవ్ రీడింగ్స్",
    heroTitle1: "వ్యవసాయం,",
    heroTitle2: " కనెక్టెడ్",
    heroTitle3: "మట్టి నుంచి స్క్రీన్ వరకు.",
    heroBody: "CropConnect పొలం నుంచి ఫోన్ వరకు పనిచేసే IoT ప్లాట్‌ఫామ్. సెన్సర్లు మట్టి, నీరు, వాతావరణాన్ని కొలిచి ఉపయోగకరమైన నిర్ణయాలుగా మారుస్తాయి.",
    explore: "ప్లాట్‌ఫామ్ చూడండి",
    talkTeam: "టీమ్‌తో మాట్లాడండి",
    heroFacts: ["7+ భారతీయ భాషలు", "తక్కువ సిగ్నల్‌లో ఆఫ్‌లైన్", "హార్డ్‌వేర్-రెడీ REST API"],
    benefitsTitle: "రైతులు అనుభవించే ప్రయోజనాలు",
    featuresTitle: "రైతు కోసం నిర్మితం,",
    featuresItalic: " ఇంజనీర్ కోసం కాదు.",
    appTitle: "రైతు",
    appItalic: " తన భాషలో.",
  },
  ta: {
    nav: ["மாதிரி", "அம்சங்கள்", "எப்படி வேலை செய்கிறது", "இலக்குகள்", "சூழல்", "தொடர்பு"],
    login: "உள்நுழை",
    signin: "சைன் இன்",
    getInTouch: "தொடர்பு கொள்ள",
    heroBadge: "ஸ்மார்ட் விவசாயம் · IoT · நேரடி அளவீடுகள்",
    heroTitle1: "விவசாயம்,",
    heroTitle2: " இணைந்தது",
    heroTitle3: "மண்ணிலிருந்து திரை வரை.",
    heroBody: "CropConnect என்பது வயலிலிருந்து தொலைபேசி வரை இயங்கும் IoT தளம். சென்சார்கள் மண், நீர், காலநிலையை அளந்து உடனடி முடிவுகளாக மாற்றும்.",
    explore: "தளத்தை பார்க்க",
    talkTeam: "குழுவுடன் பேச",
    heroFacts: ["7+ இந்திய மொழிகள்", "குறைந்த சிக்னலில் ஆஃப்லைன்", "ஹார்ட்வேர்-ரெடி REST API"],
    benefitsTitle: "விவசாயிகள் உணரும் நன்மைகள்",
    featuresTitle: "விவசாயிக்காக உருவாக்கப்பட்டது,",
    featuresItalic: " பொறியாளருக்காக அல்ல.",
    appTitle: "விவசாயியின்",
    appItalic: " சொந்த மொழியில்.",
  },
  bn: {
    nav: ["প্রোটোটাইপ", "ফিচার", "কিভাবে কাজ করে", "লক্ষ্য", "ইকোসিস্টেম", "যোগাযোগ"],
    login: "লগইন",
    signin: "সাইন ইন",
    getInTouch: "যোগাযোগ করুন",
    heroBadge: "স্মার্ট কৃষি · IoT · লাইভ রিডিং",
    heroTitle1: "কৃষি,",
    heroTitle2: " সংযুক্ত",
    heroTitle3: "মাটি থেকে স্ক্রিনে.",
    heroBody: "CropConnect মাঠ থেকে ফোন পর্যন্ত একটি IoT প্ল্যাটফর্ম. সেন্সর মাটি, জল ও আবহাওয়া মেপে তাৎক্ষণিক সিদ্ধান্তে সাহায্য করে.",
    explore: "প্ল্যাটফর্ম দেখুন",
    talkTeam: "টিমের সাথে কথা বলুন",
    heroFacts: ["7+ ভারতীয় ভাষা", "কম সিগনালে অফলাইন", "হার্ডওয়্যার-রেডি REST API"],
    benefitsTitle: "কৃষকের অনুভব করা সুবিধা",
    featuresTitle: "কৃষকের জন্য তৈরি,",
    featuresItalic: " ইঞ্জিনিয়ারের জন্য নয়.",
    appTitle: "কৃষকের",
    appItalic: " নিজের ভাষায়.",
  },
  kn: {
    nav: ["ಪ್ರೋಟೋಟೈಪ್", "ವೈಶಿಷ್ಟ್ಯಗಳು", "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", "ಗುರಿಗಳು", "ಪರಿಸರ", "ಸಂಪರ್ಕ"],
    login: "ಲಾಗಿನ್",
    signin: "ಸೈನ್ ಇನ್",
    getInTouch: "ಸಂಪರ್ಕಿಸಿ",
    heroBadge: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ · IoT · ಲೈವ್ ರೀಡಿಂಗ್ಸ್",
    heroTitle1: "ಕೃಷಿ,",
    heroTitle2: " ಸಂಪರ್ಕಿತ",
    heroTitle3: "ಮಣ್ಣಿನಿಂದ ಪರದೆವರೆಗೆ.",
    heroBody: "CropConnect ಹೊಲದಿಂದ ಫೋನ್‌ವರೆಗೆ ಕೆಲಸ ಮಾಡುವ IoT ವೇದಿಕೆ. ಸೆನ್ಸರ್‌ಗಳು ಮಣ್ಣು, ನೀರು ಮತ್ತು ಹವಾಮಾನವನ್ನು ಅಳೆಯುತ್ತವೆ ಮತ್ತು ತಕ್ಷಣದ ನಿರ್ಧಾರಗಳಿಗೆ ಸಹಾಯ ಮಾಡುತ್ತವೆ.",
    explore: "ವೇದಿಕೆಯನ್ನು ನೋಡಿ",
    talkTeam: "ತಂಡದ ಜೊತೆ ಮಾತನಾಡಿ",
    heroFacts: ["7+ ಭಾರತೀಯ ಭಾಷೆಗಳು", "ಕಡಿಮೆ ಸಿಗ್ನಲ್‌ನಲ್ಲಿ ಆಫ್‌ಲೈನ್", "ಹಾರ್ಡ್‌ವೇರ್-ರೆಡಿ REST API"],
    benefitsTitle: "ರೈತರಿಗೆ ಕಾಣುವ ಲಾಭಗಳು",
    featuresTitle: "ರೈತನಿಗಾಗಿ ನಿರ್ಮಿತ,",
    featuresItalic: " ಎಂಜಿನಿಯರ್‌ಗಾಗಿ ಅಲ್ಲ.",
    appTitle: "ರೈತನ",
    appItalic: " ತನ್ನ ಭಾಷೆಯಲ್ಲಿ.",
  },
};

const LandingLanguageContext = createContext(null);

export function LandingLanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("cropconnect-language") || "en"
  );

  const value = useMemo(() => {
    const selected = { ...common.en, ...(common[language] || {}) };
    return {
      language,
      setLanguage: (next) => {
        localStorage.setItem("cropconnect-language", next);
        setLanguage(next);
      },
      t: (key) => selected[key] || common.en[key] || key,
    };
  }, [language]);

  return (
    <LandingLanguageContext.Provider value={value}>
      {children}
    </LandingLanguageContext.Provider>
  );
}

export function useLandingLanguage() {
  const context = useContext(LandingLanguageContext);
  if (!context) {
    throw new Error("useLandingLanguage must be used inside LandingLanguageProvider");
  }
  return context;
}
